#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrulyEmpWebService.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="consumeNew")]
	public partial class CanteenDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertt_UserConfig(t_UserConfig instance);
    partial void Updatet_UserConfig(t_UserConfig instance);
    partial void Deletet_UserConfig(t_UserConfig instance);
    #endregion
		
		public CanteenDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["consumeNewConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CanteenDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CanteenDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CanteenDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CanteenDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<t_UserConfig> t_UserConfig
		{
			get
			{
				return this.GetTable<t_UserConfig>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.laijq20161105_001")]
		public ISingleResult<laijq20161105_001Result> laijq20161105_001()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<laijq20161105_001Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.laijq20161105_002")]
		public ISingleResult<laijq20161105_002Result> laijq20161105_002()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<laijq20161105_002Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ljq20160323_001")]
		public ISingleResult<ljq20160323_001Result> ljq20160323_001([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpNo", DbType="VarChar(255)")] string empNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BegDay", DbType="VarChar(255)")] string begDay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDay", DbType="VarChar(255)")] string endDay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empNo, begDay, endDay);
			return ((ISingleResult<ljq20160323_001Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ljq20160323_002")]
		public ISingleResult<ljq20160323_002Result> ljq20160323_002([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpNo", DbType="VarChar(255)")] string empNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empNo);
			return ((ISingleResult<ljq20160323_002Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ljq20160323_003")]
		public ISingleResult<ljq20160323_003Result> ljq20160323_003([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpNo", DbType="VarChar(255)")] string empNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BegDay", DbType="VarChar(255)")] string begDay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EndDay", DbType="VarChar(255)")] string endDay)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empNo, begDay, endDay);
			return ((ISingleResult<ljq20160323_003Result>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ljq20161019")]
		public int ljq20161019([global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmpNo", DbType="NVarChar(255)")] string empNo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="NVarChar(20)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), empNo, status);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.t_UserConfig")]
	public partial class t_UserConfig : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FID;
		
		private string _FNumber;
		
		private string _FPhone;
		
		private string _FPassword;
		
		private decimal _FQuota;
		
		private string _FStatus;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFIDChanging(int value);
    partial void OnFIDChanged();
    partial void OnFNumberChanging(string value);
    partial void OnFNumberChanged();
    partial void OnFPhoneChanging(string value);
    partial void OnFPhoneChanged();
    partial void OnFPasswordChanging(string value);
    partial void OnFPasswordChanged();
    partial void OnFQuotaChanging(decimal value);
    partial void OnFQuotaChanged();
    partial void OnFStatusChanging(string value);
    partial void OnFStatusChanged();
    #endregion
		
		public t_UserConfig()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FID
		{
			get
			{
				return this._FID;
			}
			set
			{
				if ((this._FID != value))
				{
					this.OnFIDChanging(value);
					this.SendPropertyChanging();
					this._FID = value;
					this.SendPropertyChanged("FID");
					this.OnFIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FNumber
		{
			get
			{
				return this._FNumber;
			}
			set
			{
				if ((this._FNumber != value))
				{
					this.OnFNumberChanging(value);
					this.SendPropertyChanging();
					this._FNumber = value;
					this.SendPropertyChanged("FNumber");
					this.OnFNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPhone", DbType="NVarChar(50)")]
		public string FPhone
		{
			get
			{
				return this._FPhone;
			}
			set
			{
				if ((this._FPhone != value))
				{
					this.OnFPhoneChanging(value);
					this.SendPropertyChanging();
					this._FPhone = value;
					this.SendPropertyChanged("FPhone");
					this.OnFPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FPassword", DbType="NVarChar(MAX)")]
		public string FPassword
		{
			get
			{
				return this._FPassword;
			}
			set
			{
				if ((this._FPassword != value))
				{
					this.OnFPasswordChanging(value);
					this.SendPropertyChanging();
					this._FPassword = value;
					this.SendPropertyChanged("FPassword");
					this.OnFPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FQuota", DbType="Money NOT NULL")]
		public decimal FQuota
		{
			get
			{
				return this._FQuota;
			}
			set
			{
				if ((this._FQuota != value))
				{
					this.OnFQuotaChanging(value);
					this.SendPropertyChanging();
					this._FQuota = value;
					this.SendPropertyChanged("FQuota");
					this.OnFQuotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FStatus", DbType="NVarChar(5)")]
		public string FStatus
		{
			get
			{
				return this._FStatus;
			}
			set
			{
				if ((this._FStatus != value))
				{
					this.OnFStatusChanging(value);
					this.SendPropertyChanging();
					this._FStatus = value;
					this.SendPropertyChanged("FStatus");
					this.OnFStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class laijq20161105_001Result
	{
		
		private string _FWeek;
		
		private string _FFloor;
		
		private System.Nullable<int> _SumMonConsume;
		
		public laijq20161105_001Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FWeek", DbType="NVarChar(30)")]
		public string FWeek
		{
			get
			{
				return this._FWeek;
			}
			set
			{
				if ((this._FWeek != value))
				{
					this._FWeek = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FFloor", DbType="NVarChar(255)")]
		public string FFloor
		{
			get
			{
				return this._FFloor;
			}
			set
			{
				if ((this._FFloor != value))
				{
					this._FFloor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SumMonConsume", DbType="Int")]
		public System.Nullable<int> SumMonConsume
		{
			get
			{
				return this._SumMonConsume;
			}
			set
			{
				if ((this._SumMonConsume != value))
				{
					this._SumMonConsume = value;
				}
			}
		}
	}
	
	public partial class laijq20161105_002Result
	{
		
		private string _FType;
		
		private System.Nullable<int> _Total;
		
		public laijq20161105_002Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FType", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string FType
		{
			get
			{
				return this._FType;
			}
			set
			{
				if ((this._FType != value))
				{
					this._FType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class ljq20160323_001Result
	{
		
		private System.DateTime _消费时间;
		
		private string _消费场所;
		
		private decimal _消费金额;
		
		private string _餐别;
		
		public ljq20160323_001Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_消费时间", DbType="DateTime NOT NULL")]
		public System.DateTime 消费时间
		{
			get
			{
				return this._消费时间;
			}
			set
			{
				if ((this._消费时间 != value))
				{
					this._消费时间 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_消费场所", DbType="VarChar(50)")]
		public string 消费场所
		{
			get
			{
				return this._消费场所;
			}
			set
			{
				if ((this._消费场所 != value))
				{
					this._消费场所 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_消费金额", DbType="SmallMoney NOT NULL")]
		public decimal 消费金额
		{
			get
			{
				return this._消费金额;
			}
			set
			{
				if ((this._消费金额 != value))
				{
					this._消费金额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_餐别", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string 餐别
		{
			get
			{
				return this._餐别;
			}
			set
			{
				if ((this._餐别 != value))
				{
					this._餐别 = value;
				}
			}
		}
	}
	
	public partial class ljq20160323_002Result
	{
		
		private System.Nullable<System.DateTime> _DatLastConsumeTime;
		
		private string _FStatus;
		
		private System.Nullable<decimal> _MonBalance;
		
		public ljq20160323_002Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatLastConsumeTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> DatLastConsumeTime
		{
			get
			{
				return this._DatLastConsumeTime;
			}
			set
			{
				if ((this._DatLastConsumeTime != value))
				{
					this._DatLastConsumeTime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FStatus", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string FStatus
		{
			get
			{
				return this._FStatus;
			}
			set
			{
				if ((this._FStatus != value))
				{
					this._FStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MonBalance", DbType="Money")]
		public System.Nullable<decimal> MonBalance
		{
			get
			{
				return this._MonBalance;
			}
			set
			{
				if ((this._MonBalance != value))
				{
					this._MonBalance = value;
				}
			}
		}
	}
	
	public partial class ljq20160323_003Result
	{
		
		private System.Nullable<decimal> _充值前金额;
		
		private System.Nullable<decimal> _充值金额;
		
		private System.Nullable<decimal> _充值后金额;
		
		private System.DateTime _充值时间;
		
		private string _充值场所;
		
		public ljq20160323_003Result()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_充值前金额", DbType="Money")]
		public System.Nullable<decimal> 充值前金额
		{
			get
			{
				return this._充值前金额;
			}
			set
			{
				if ((this._充值前金额 != value))
				{
					this._充值前金额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_充值金额", DbType="Money")]
		public System.Nullable<decimal> 充值金额
		{
			get
			{
				return this._充值金额;
			}
			set
			{
				if ((this._充值金额 != value))
				{
					this._充值金额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_充值后金额", DbType="Money")]
		public System.Nullable<decimal> 充值后金额
		{
			get
			{
				return this._充值后金额;
			}
			set
			{
				if ((this._充值后金额 != value))
				{
					this._充值后金额 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_充值时间", DbType="DateTime NOT NULL")]
		public System.DateTime 充值时间
		{
			get
			{
				return this._充值时间;
			}
			set
			{
				if ((this._充值时间 != value))
				{
					this._充值时间 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_充值场所", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string 充值场所
		{
			get
			{
				return this._充值场所;
			}
			set
			{
				if ((this._充值场所 != value))
				{
					this._充值场所 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
