#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrulyEmpWebService.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ICAudit")]
	public partial class EmpDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insertei_users(ei_users instance);
    partial void Updateei_users(ei_users instance);
    partial void Deleteei_users(ei_users instance);
    partial void Insertei_authority(ei_authority instance);
    partial void Updateei_authority(ei_authority instance);
    partial void Deleteei_authority(ei_authority instance);
    partial void Insertei_groupAuthority(ei_groupAuthority instance);
    partial void Updateei_groupAuthority(ei_groupAuthority instance);
    partial void Deleteei_groupAuthority(ei_groupAuthority instance);
    partial void Insertei_groups(ei_groups instance);
    partial void Updateei_groups(ei_groups instance);
    partial void Deleteei_groups(ei_groups instance);
    partial void Insertei_groupUser(ei_groupUser instance);
    partial void Updateei_groupUser(ei_groupUser instance);
    partial void Deleteei_groupUser(ei_groupUser instance);
    partial void Insertei_event_log_android(ei_event_log_android instance);
    partial void Updateei_event_log_android(ei_event_log_android instance);
    partial void Deleteei_event_log_android(ei_event_log_android instance);
    partial void Insertei_specialUsers(ei_specialUsers instance);
    partial void Updateei_specialUsers(ei_specialUsers instance);
    partial void Deleteei_specialUsers(ei_specialUsers instance);
    #endregion
		
		public EmpDBDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ICAuditConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public EmpDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public EmpDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ei_users> ei_users
		{
			get
			{
				return this.GetTable<ei_users>();
			}
		}
		
		public System.Data.Linq.Table<ei_authority> ei_authority
		{
			get
			{
				return this.GetTable<ei_authority>();
			}
		}
		
		public System.Data.Linq.Table<ei_groupAuthority> ei_groupAuthority
		{
			get
			{
				return this.GetTable<ei_groupAuthority>();
			}
		}
		
		public System.Data.Linq.Table<ei_groups> ei_groups
		{
			get
			{
				return this.GetTable<ei_groups>();
			}
		}
		
		public System.Data.Linq.Table<ei_groupUser> ei_groupUser
		{
			get
			{
				return this.GetTable<ei_groupUser>();
			}
		}
		
		public System.Data.Linq.Table<vw_ei_simple_users> vw_ei_simple_users
		{
			get
			{
				return this.GetTable<vw_ei_simple_users>();
			}
		}
		
		public System.Data.Linq.Table<vw_ei_users> vw_ei_users
		{
			get
			{
				return this.GetTable<vw_ei_users>();
			}
		}
		
		public System.Data.Linq.Table<ei_event_log_android> ei_event_log_android
		{
			get
			{
				return this.GetTable<ei_event_log_android>();
			}
		}
		
		public System.Data.Linq.Table<ei_specialUsers> ei_specialUsers
		{
			get
			{
				return this.GetTable<ei_specialUsers>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetDormChargeMonth")]
		public ISingleResult<GetDormChargeMonthResult> GetDormChargeMonth()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetDormChargeMonthResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetDormFeeByMonth")]
		public ISingleResult<GetDormFeeByMonthResult> GetDormFeeByMonth([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string yearMonth, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string salaryNo)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), yearMonth, salaryNo);
			return ((ISingleResult<GetDormFeeByMonthResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetEmpDormInfo")]
		public ISingleResult<GetEmpDormInfoResult> GetEmpDormInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string card_no)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), card_no);
			return ((ISingleResult<GetEmpDormInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetHREmpInfo")]
		public ISingleResult<GetHREmpInfoResult> GetHREmpInfo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string card_no)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), card_no);
			return ((ISingleResult<GetHREmpInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetHREmpStatus")]
		public ISingleResult<GetHREmpStatusResult> GetHREmpStatus([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string card_no)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), card_no);
			return ((ISingleResult<GetHREmpStatusResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ValidateDormStatus")]
		public ISingleResult<ValidateDormStatusResult> ValidateDormStatus([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string account)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), account);
			return ((ISingleResult<ValidateDormStatusResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SearchHREmp")]
		public ISingleResult<SearchHREmpResult> SearchHREmp([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string searchValue)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchValue);
			return ((ISingleResult<SearchHREmpResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ei_users")]
	public partial class ei_users : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _card_number;
		
		private string _name;
		
		private string _email;
		
		private string _phone;
		
		private System.Nullable<bool> _forbit_flag;
		
		private System.Nullable<System.DateTime> _create_date;
		
		private System.Nullable<System.DateTime> _last_login_date;
		
		private string _password;
		
		private System.Nullable<int> _fail_times;
		
		private string _sex;
		
		private string _id_number;
		
		private string _salary_no;
		
		private string _short_phone;
		
		private System.Data.Linq.Binary _short_portrait;
		
		private EntitySet<ei_groupUser> _ei_groupUser;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncard_numberChanging(string value);
    partial void Oncard_numberChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void Onforbit_flagChanging(System.Nullable<bool> value);
    partial void Onforbit_flagChanged();
    partial void Oncreate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_dateChanged();
    partial void Onlast_login_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onlast_login_dateChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void Onfail_timesChanging(System.Nullable<int> value);
    partial void Onfail_timesChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void Onid_numberChanging(string value);
    partial void Onid_numberChanged();
    partial void Onsalary_noChanging(string value);
    partial void Onsalary_noChanged();
    partial void Onshort_phoneChanging(string value);
    partial void Onshort_phoneChanged();
    partial void Onshort_portraitChanging(System.Data.Linq.Binary value);
    partial void Onshort_portraitChanged();
    #endregion
		
		public ei_users()
		{
			this._ei_groupUser = new EntitySet<ei_groupUser>(new Action<ei_groupUser>(this.attach_ei_groupUser), new Action<ei_groupUser>(this.detach_ei_groupUser));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_number", DbType="VarChar(50)")]
		public string card_number
		{
			get
			{
				return this._card_number;
			}
			set
			{
				if ((this._card_number != value))
				{
					this.Oncard_numberChanging(value);
					this.SendPropertyChanging();
					this._card_number = value;
					this.SendPropertyChanged("card_number");
					this.Oncard_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_forbit_flag", DbType="Bit")]
		public System.Nullable<bool> forbit_flag
		{
			get
			{
				return this._forbit_flag;
			}
			set
			{
				if ((this._forbit_flag != value))
				{
					this.Onforbit_flagChanging(value);
					this.SendPropertyChanging();
					this._forbit_flag = value;
					this.SendPropertyChanged("forbit_flag");
					this.Onforbit_flagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_login_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> last_login_date
		{
			get
			{
				return this._last_login_date;
			}
			set
			{
				if ((this._last_login_date != value))
				{
					this.Onlast_login_dateChanging(value);
					this.SendPropertyChanging();
					this._last_login_date = value;
					this.SendPropertyChanged("last_login_date");
					this.Onlast_login_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fail_times", DbType="Int")]
		public System.Nullable<int> fail_times
		{
			get
			{
				return this._fail_times;
			}
			set
			{
				if ((this._fail_times != value))
				{
					this.Onfail_timesChanging(value);
					this.SendPropertyChanging();
					this._fail_times = value;
					this.SendPropertyChanged("fail_times");
					this.Onfail_timesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="VarChar(10)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_number", DbType="VarChar(50)")]
		public string id_number
		{
			get
			{
				return this._id_number;
			}
			set
			{
				if ((this._id_number != value))
				{
					this.Onid_numberChanging(value);
					this.SendPropertyChanging();
					this._id_number = value;
					this.SendPropertyChanged("id_number");
					this.Onid_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary_no", DbType="VarChar(20)")]
		public string salary_no
		{
			get
			{
				return this._salary_no;
			}
			set
			{
				if ((this._salary_no != value))
				{
					this.Onsalary_noChanging(value);
					this.SendPropertyChanging();
					this._salary_no = value;
					this.SendPropertyChanged("salary_no");
					this.Onsalary_noChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_short_phone", DbType="VarChar(50)")]
		public string short_phone
		{
			get
			{
				return this._short_phone;
			}
			set
			{
				if ((this._short_phone != value))
				{
					this.Onshort_phoneChanging(value);
					this.SendPropertyChanging();
					this._short_phone = value;
					this.SendPropertyChanged("short_phone");
					this.Onshort_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_short_portrait", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary short_portrait
		{
			get
			{
				return this._short_portrait;
			}
			set
			{
				if ((this._short_portrait != value))
				{
					this.Onshort_portraitChanging(value);
					this.SendPropertyChanging();
					this._short_portrait = value;
					this.SendPropertyChanged("short_portrait");
					this.Onshort_portraitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ei_users_ei_groupUser", Storage="_ei_groupUser", ThisKey="id", OtherKey="user_id")]
		public EntitySet<ei_groupUser> ei_groupUser
		{
			get
			{
				return this._ei_groupUser;
			}
			set
			{
				this._ei_groupUser.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ei_groupUser(ei_groupUser entity)
		{
			this.SendPropertyChanging();
			entity.ei_users = this;
		}
		
		private void detach_ei_groupUser(ei_groupUser entity)
		{
			this.SendPropertyChanging();
			entity.ei_users = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ei_authority")]
	public partial class ei_authority : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<decimal> _number;
		
		private string _name;
		
		private string _en_name;
		
		private string _description;
		
		private string _controler_name;
		
		private string _action_name;
		
		private string _iconcls;
		
		private EntitySet<ei_groupAuthority> _ei_groupAuthority;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnumberChanging(System.Nullable<decimal> value);
    partial void OnnumberChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void Onen_nameChanging(string value);
    partial void Onen_nameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Oncontroler_nameChanging(string value);
    partial void Oncontroler_nameChanged();
    partial void Onaction_nameChanging(string value);
    partial void Onaction_nameChanged();
    partial void OniconclsChanging(string value);
    partial void OniconclsChanged();
    #endregion
		
		public ei_authority()
		{
			this._ei_groupAuthority = new EntitySet<ei_groupAuthority>(new Action<ei_groupAuthority>(this.attach_ei_groupAuthority), new Action<ei_groupAuthority>(this.detach_ei_groupAuthority));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number", DbType="Decimal(6,2)")]
		public System.Nullable<decimal> number
		{
			get
			{
				return this._number;
			}
			set
			{
				if ((this._number != value))
				{
					this.OnnumberChanging(value);
					this.SendPropertyChanging();
					this._number = value;
					this.SendPropertyChanged("number");
					this.OnnumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_en_name", DbType="VarChar(50)")]
		public string en_name
		{
			get
			{
				return this._en_name;
			}
			set
			{
				if ((this._en_name != value))
				{
					this.Onen_nameChanging(value);
					this.SendPropertyChanging();
					this._en_name = value;
					this.SendPropertyChanged("en_name");
					this.Onen_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(100)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_controler_name", DbType="VarChar(30)")]
		public string controler_name
		{
			get
			{
				return this._controler_name;
			}
			set
			{
				if ((this._controler_name != value))
				{
					this.Oncontroler_nameChanging(value);
					this.SendPropertyChanging();
					this._controler_name = value;
					this.SendPropertyChanged("controler_name");
					this.Oncontroler_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_action_name", DbType="VarChar(30)")]
		public string action_name
		{
			get
			{
				return this._action_name;
			}
			set
			{
				if ((this._action_name != value))
				{
					this.Onaction_nameChanging(value);
					this.SendPropertyChanging();
					this._action_name = value;
					this.SendPropertyChanged("action_name");
					this.Onaction_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iconcls", DbType="VarChar(50)")]
		public string iconcls
		{
			get
			{
				return this._iconcls;
			}
			set
			{
				if ((this._iconcls != value))
				{
					this.OniconclsChanging(value);
					this.SendPropertyChanging();
					this._iconcls = value;
					this.SendPropertyChanged("iconcls");
					this.OniconclsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ei_authority_ei_groupAuthority", Storage="_ei_groupAuthority", ThisKey="id", OtherKey="authority_id")]
		public EntitySet<ei_groupAuthority> ei_groupAuthority
		{
			get
			{
				return this._ei_groupAuthority;
			}
			set
			{
				this._ei_groupAuthority.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ei_groupAuthority(ei_groupAuthority entity)
		{
			this.SendPropertyChanging();
			entity.ei_authority = this;
		}
		
		private void detach_ei_groupAuthority(ei_groupAuthority entity)
		{
			this.SendPropertyChanging();
			entity.ei_authority = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ei_groupAuthority")]
	public partial class ei_groupAuthority : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _group_id;
		
		private System.Nullable<int> _authority_id;
		
		private EntityRef<ei_authority> _ei_authority;
		
		private EntityRef<ei_groups> _ei_groups;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ongroup_idChanging(System.Nullable<int> value);
    partial void Ongroup_idChanged();
    partial void Onauthority_idChanging(System.Nullable<int> value);
    partial void Onauthority_idChanged();
    #endregion
		
		public ei_groupAuthority()
		{
			this._ei_authority = default(EntityRef<ei_authority>);
			this._ei_groups = default(EntityRef<ei_groups>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_id", DbType="Int")]
		public System.Nullable<int> group_id
		{
			get
			{
				return this._group_id;
			}
			set
			{
				if ((this._group_id != value))
				{
					if (this._ei_groups.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongroup_idChanging(value);
					this.SendPropertyChanging();
					this._group_id = value;
					this.SendPropertyChanged("group_id");
					this.Ongroup_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_authority_id", DbType="Int")]
		public System.Nullable<int> authority_id
		{
			get
			{
				return this._authority_id;
			}
			set
			{
				if ((this._authority_id != value))
				{
					if (this._ei_authority.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onauthority_idChanging(value);
					this.SendPropertyChanging();
					this._authority_id = value;
					this.SendPropertyChanged("authority_id");
					this.Onauthority_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ei_authority_ei_groupAuthority", Storage="_ei_authority", ThisKey="authority_id", OtherKey="id", IsForeignKey=true)]
		public ei_authority ei_authority
		{
			get
			{
				return this._ei_authority.Entity;
			}
			set
			{
				ei_authority previousValue = this._ei_authority.Entity;
				if (((previousValue != value) 
							|| (this._ei_authority.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ei_authority.Entity = null;
						previousValue.ei_groupAuthority.Remove(this);
					}
					this._ei_authority.Entity = value;
					if ((value != null))
					{
						value.ei_groupAuthority.Add(this);
						this._authority_id = value.id;
					}
					else
					{
						this._authority_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("ei_authority");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ei_groups_ei_groupAuthority", Storage="_ei_groups", ThisKey="group_id", OtherKey="id", IsForeignKey=true)]
		public ei_groups ei_groups
		{
			get
			{
				return this._ei_groups.Entity;
			}
			set
			{
				ei_groups previousValue = this._ei_groups.Entity;
				if (((previousValue != value) 
							|| (this._ei_groups.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ei_groups.Entity = null;
						previousValue.ei_groupAuthority.Remove(this);
					}
					this._ei_groups.Entity = value;
					if ((value != null))
					{
						value.ei_groupAuthority.Add(this);
						this._group_id = value.id;
					}
					else
					{
						this._group_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("ei_groups");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ei_groups")]
	public partial class ei_groups : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _name;
		
		private string _description;
		
		private EntitySet<ei_groupAuthority> _ei_groupAuthority;
		
		private EntitySet<ei_groupUser> _ei_groupUser;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public ei_groups()
		{
			this._ei_groupAuthority = new EntitySet<ei_groupAuthority>(new Action<ei_groupAuthority>(this.attach_ei_groupAuthority), new Action<ei_groupAuthority>(this.detach_ei_groupAuthority));
			this._ei_groupUser = new EntitySet<ei_groupUser>(new Action<ei_groupUser>(this.attach_ei_groupUser), new Action<ei_groupUser>(this.detach_ei_groupUser));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(50)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(100)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ei_groups_ei_groupAuthority", Storage="_ei_groupAuthority", ThisKey="id", OtherKey="group_id")]
		public EntitySet<ei_groupAuthority> ei_groupAuthority
		{
			get
			{
				return this._ei_groupAuthority;
			}
			set
			{
				this._ei_groupAuthority.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ei_groups_ei_groupUser", Storage="_ei_groupUser", ThisKey="id", OtherKey="group_id")]
		public EntitySet<ei_groupUser> ei_groupUser
		{
			get
			{
				return this._ei_groupUser;
			}
			set
			{
				this._ei_groupUser.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ei_groupAuthority(ei_groupAuthority entity)
		{
			this.SendPropertyChanging();
			entity.ei_groups = this;
		}
		
		private void detach_ei_groupAuthority(ei_groupAuthority entity)
		{
			this.SendPropertyChanging();
			entity.ei_groups = null;
		}
		
		private void attach_ei_groupUser(ei_groupUser entity)
		{
			this.SendPropertyChanging();
			entity.ei_groups = this;
		}
		
		private void detach_ei_groupUser(ei_groupUser entity)
		{
			this.SendPropertyChanging();
			entity.ei_groups = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ei_groupUser")]
	public partial class ei_groupUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _group_id;
		
		private System.Nullable<int> _user_id;
		
		private EntityRef<ei_groups> _ei_groups;
		
		private EntityRef<ei_users> _ei_users;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Ongroup_idChanging(System.Nullable<int> value);
    partial void Ongroup_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    #endregion
		
		public ei_groupUser()
		{
			this._ei_groups = default(EntityRef<ei_groups>);
			this._ei_users = default(EntityRef<ei_users>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_group_id", DbType="Int")]
		public System.Nullable<int> group_id
		{
			get
			{
				return this._group_id;
			}
			set
			{
				if ((this._group_id != value))
				{
					if (this._ei_groups.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ongroup_idChanging(value);
					this.SendPropertyChanging();
					this._group_id = value;
					this.SendPropertyChanged("group_id");
					this.Ongroup_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._ei_users.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ei_groups_ei_groupUser", Storage="_ei_groups", ThisKey="group_id", OtherKey="id", IsForeignKey=true)]
		public ei_groups ei_groups
		{
			get
			{
				return this._ei_groups.Entity;
			}
			set
			{
				ei_groups previousValue = this._ei_groups.Entity;
				if (((previousValue != value) 
							|| (this._ei_groups.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ei_groups.Entity = null;
						previousValue.ei_groupUser.Remove(this);
					}
					this._ei_groups.Entity = value;
					if ((value != null))
					{
						value.ei_groupUser.Add(this);
						this._group_id = value.id;
					}
					else
					{
						this._group_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("ei_groups");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ei_users_ei_groupUser", Storage="_ei_users", ThisKey="user_id", OtherKey="id", IsForeignKey=true)]
		public ei_users ei_users
		{
			get
			{
				return this._ei_users.Entity;
			}
			set
			{
				ei_users previousValue = this._ei_users.Entity;
				if (((previousValue != value) 
							|| (this._ei_users.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ei_users.Entity = null;
						previousValue.ei_groupUser.Remove(this);
					}
					this._ei_users.Entity = value;
					if ((value != null))
					{
						value.ei_groupUser.Add(this);
						this._user_id = value.id;
					}
					else
					{
						this._user_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("ei_users");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_ei_simple_users")]
	public partial class vw_ei_simple_users
	{
		
		private int _id;
		
		private string _card_number;
		
		private string _name;
		
		private System.Nullable<bool> _forbit_flag;
		
		private string _sex;
		
		private string _id_number;
		
		private string _salary_no;
		
		private string _dep_name;
		
		private string _short_dep_name;
		
		public vw_ei_simple_users()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_number", DbType="VarChar(50)")]
		public string card_number
		{
			get
			{
				return this._card_number;
			}
			set
			{
				if ((this._card_number != value))
				{
					this._card_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_forbit_flag", DbType="Bit")]
		public System.Nullable<bool> forbit_flag
		{
			get
			{
				return this._forbit_flag;
			}
			set
			{
				if ((this._forbit_flag != value))
				{
					this._forbit_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="VarChar(10)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this._sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_number", DbType="VarChar(50)")]
		public string id_number
		{
			get
			{
				return this._id_number;
			}
			set
			{
				if ((this._id_number != value))
				{
					this._id_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary_no", DbType="VarChar(20)")]
		public string salary_no
		{
			get
			{
				return this._salary_no;
			}
			set
			{
				if ((this._salary_no != value))
				{
					this._salary_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_name", DbType="VarChar(100)")]
		public string dep_name
		{
			get
			{
				return this._dep_name;
			}
			set
			{
				if ((this._dep_name != value))
				{
					this._dep_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_short_dep_name", DbType="VarChar(200)")]
		public string short_dep_name
		{
			get
			{
				return this._short_dep_name;
			}
			set
			{
				if ((this._short_dep_name != value))
				{
					this._short_dep_name = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vw_ei_users")]
	public partial class vw_ei_users
	{
		
		private int _id;
		
		private string _card_number;
		
		private string _name;
		
		private string _email;
		
		private string _phone;
		
		private System.Nullable<bool> _forbit_flag;
		
		private System.Nullable<System.DateTime> _create_date;
		
		private System.Nullable<System.DateTime> _last_login_date;
		
		private string _sex;
		
		private string _id_number;
		
		private string _salary_no;
		
		private System.Data.Linq.Binary _short_portrait;
		
		private string _dep_name;
		
		private string _short_dep_name;
		
		private string _short_phone;
		
		public vw_ei_users()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL")]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_number", DbType="VarChar(50)")]
		public string card_number
		{
			get
			{
				return this._card_number;
			}
			set
			{
				if ((this._card_number != value))
				{
					this._card_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="VarChar(100)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(50)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_forbit_flag", DbType="Bit")]
		public System.Nullable<bool> forbit_flag
		{
			get
			{
				return this._forbit_flag;
			}
			set
			{
				if ((this._forbit_flag != value))
				{
					this._forbit_flag = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this._create_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_last_login_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> last_login_date
		{
			get
			{
				return this._last_login_date;
			}
			set
			{
				if ((this._last_login_date != value))
				{
					this._last_login_date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="VarChar(10)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this._sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_number", DbType="VarChar(50)")]
		public string id_number
		{
			get
			{
				return this._id_number;
			}
			set
			{
				if ((this._id_number != value))
				{
					this._id_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salary_no", DbType="VarChar(20)")]
		public string salary_no
		{
			get
			{
				return this._salary_no;
			}
			set
			{
				if ((this._salary_no != value))
				{
					this._salary_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_short_portrait", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary short_portrait
		{
			get
			{
				return this._short_portrait;
			}
			set
			{
				if ((this._short_portrait != value))
				{
					this._short_portrait = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dep_name", DbType="VarChar(100)")]
		public string dep_name
		{
			get
			{
				return this._dep_name;
			}
			set
			{
				if ((this._dep_name != value))
				{
					this._dep_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_short_dep_name", DbType="VarChar(200)")]
		public string short_dep_name
		{
			get
			{
				return this._short_dep_name;
			}
			set
			{
				if ((this._short_dep_name != value))
				{
					this._short_dep_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_short_phone", DbType="VarChar(50)")]
		public string short_phone
		{
			get
			{
				return this._short_phone;
			}
			set
			{
				if ((this._short_phone != value))
				{
					this._short_phone = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ei_event_log_android")]
	public partial class ei_event_log_android : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _model;
		
		private string _do_what;
		
		private System.Nullable<System.DateTime> _op_date;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnmodelChanging(string value);
    partial void OnmodelChanged();
    partial void Ondo_whatChanging(string value);
    partial void Ondo_whatChanged();
    partial void Onop_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onop_dateChanged();
    #endregion
		
		public ei_event_log_android()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_model", DbType="VarChar(50)")]
		public string model
		{
			get
			{
				return this._model;
			}
			set
			{
				if ((this._model != value))
				{
					this.OnmodelChanging(value);
					this.SendPropertyChanging();
					this._model = value;
					this.SendPropertyChanged("model");
					this.OnmodelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_do_what", DbType="VarChar(max)")]
		public string do_what
		{
			get
			{
				return this._do_what;
			}
			set
			{
				if ((this._do_what != value))
				{
					this.Ondo_whatChanging(value);
					this.SendPropertyChanging();
					this._do_what = value;
					this.SendPropertyChanged("do_what");
					this.Ondo_whatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_op_date", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> op_date
		{
			get
			{
				return this._op_date;
			}
			set
			{
				if ((this._op_date != value))
				{
					this.Onop_dateChanging(value);
					this.SendPropertyChanging();
					this._op_date = value;
					this.SendPropertyChanged("op_date");
					this.Onop_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ei_specialUsers")]
	public partial class ei_specialUsers : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _card_no;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Oncard_noChanging(string value);
    partial void Oncard_noChanged();
    #endregion
		
		public ei_specialUsers()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_card_no", DbType="VarChar(50)")]
		public string card_no
		{
			get
			{
				return this._card_no;
			}
			set
			{
				if ((this._card_no != value))
				{
					this.Oncard_noChanging(value);
					this.SendPropertyChanging();
					this._card_no = value;
					this.SendPropertyChanged("card_no");
					this.Oncard_noChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class GetDormChargeMonthResult
	{
		
		private string _year_month;
		
		public GetDormChargeMonthResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_year_month", DbType="VarChar(10)")]
		public string year_month
		{
			get
			{
				return this._year_month;
			}
			set
			{
				if ((this._year_month != value))
				{
					this._year_month = value;
				}
			}
		}
	}
	
	public partial class GetDormFeeByMonthResult
	{
		
		private string _dorm_number;
		
		private System.Nullable<decimal> _rent;
		
		private System.Nullable<decimal> _water;
		
		private System.Nullable<decimal> _electricity;
		
		private System.Nullable<decimal> _management;
		
		private decimal _repair;
		
		private decimal _fine;
		
		private decimal _others;
		
		private string _comment;
		
		private System.Nullable<decimal> _total;
		
		public GetDormFeeByMonthResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dorm_number", DbType="VarChar(50)")]
		public string dorm_number
		{
			get
			{
				return this._dorm_number;
			}
			set
			{
				if ((this._dorm_number != value))
				{
					this._dorm_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rent", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> rent
		{
			get
			{
				return this._rent;
			}
			set
			{
				if ((this._rent != value))
				{
					this._rent = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_water", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> water
		{
			get
			{
				return this._water;
			}
			set
			{
				if ((this._water != value))
				{
					this._water = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_electricity", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> electricity
		{
			get
			{
				return this._electricity;
			}
			set
			{
				if ((this._electricity != value))
				{
					this._electricity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_management", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> management
		{
			get
			{
				return this._management;
			}
			set
			{
				if ((this._management != value))
				{
					this._management = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_repair", DbType="Decimal(8,2) NOT NULL")]
		public decimal repair
		{
			get
			{
				return this._repair;
			}
			set
			{
				if ((this._repair != value))
				{
					this._repair = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fine", DbType="Decimal(8,2) NOT NULL")]
		public decimal fine
		{
			get
			{
				return this._fine;
			}
			set
			{
				if ((this._fine != value))
				{
					this._fine = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_others", DbType="Decimal(8,2) NOT NULL")]
		public decimal others
		{
			get
			{
				return this._others;
			}
			set
			{
				if ((this._others != value))
				{
					this._others = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_comment", DbType="VarChar(200)")]
		public string comment
		{
			get
			{
				return this._comment;
			}
			set
			{
				if ((this._comment != value))
				{
					this._comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(10,1)")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
	
	public partial class GetEmpDormInfoResult
	{
		
		private string _area;
		
		private string _dorm_number;
		
		private System.Nullable<System.DateTime> _in_date;
		
		public GetEmpDormInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_area", DbType="VarChar(20)")]
		public string area
		{
			get
			{
				return this._area;
			}
			set
			{
				if ((this._area != value))
				{
					this._area = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dorm_number", DbType="VarChar(50)")]
		public string dorm_number
		{
			get
			{
				return this._dorm_number;
			}
			set
			{
				if ((this._dorm_number != value))
				{
					this._dorm_number = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_in_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> in_date
		{
			get
			{
				return this._in_date;
			}
			set
			{
				if ((this._in_date != value))
				{
					this._in_date = value;
				}
			}
		}
	}
	
	public partial class GetHREmpInfoResult
	{
		
		private string _sex;
		
		private string _emp_name;
		
		private string _id_code;
		
		private string _email;
		
		private string _tp;
		
		private System.Data.Linq.Binary _zp;
		
		private string _txm;
		
		public GetHREmpInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="VarChar(2)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this._sex = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string emp_name
		{
			get
			{
				return this._emp_name;
			}
			set
			{
				if ((this._emp_name != value))
				{
					this._emp_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_code", DbType="VarChar(50)")]
		public string id_code
		{
			get
			{
				return this._id_code;
			}
			set
			{
				if ((this._id_code != value))
				{
					this._id_code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tp", DbType="VarChar(100)")]
		public string tp
		{
			get
			{
				return this._tp;
			}
			set
			{
				if ((this._tp != value))
				{
					this._tp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_zp", DbType="Image")]
		public System.Data.Linq.Binary zp
		{
			get
			{
				return this._zp;
			}
			set
			{
				if ((this._zp != value))
				{
					this._zp = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txm", DbType="VarChar(10)")]
		public string txm
		{
			get
			{
				return this._txm;
			}
			set
			{
				if ((this._txm != value))
				{
					this._txm = value;
				}
			}
		}
	}
	
	public partial class GetHREmpStatusResult
	{
		
		private string _state;
		
		public GetHREmpStatusResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_state", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string state
		{
			get
			{
				return this._state;
			}
			set
			{
				if ((this._state != value))
				{
					this._state = value;
				}
			}
		}
	}
	
	public partial class ValidateDormStatusResult
	{
		
		private string _msg;
		
		private int _suc;
		
		public ValidateDormStatusResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_msg", DbType="VarChar(28) NOT NULL", CanBeNull=false)]
		public string msg
		{
			get
			{
				return this._msg;
			}
			set
			{
				if ((this._msg != value))
				{
					this._msg = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_suc", DbType="Int NOT NULL")]
		public int suc
		{
			get
			{
				return this._suc;
			}
			set
			{
				if ((this._suc != value))
				{
					this._suc = value;
				}
			}
		}
	}
	
	public partial class SearchHREmpResult
	{
		
		private string _emp_no;
		
		private string _emp_name;
		
		public SearchHREmpResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_no", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string emp_no
		{
			get
			{
				return this._emp_no;
			}
			set
			{
				if ((this._emp_no != value))
				{
					this._emp_no = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string emp_name
		{
			get
			{
				return this._emp_name;
			}
			set
			{
				if ((this._emp_name != value))
				{
					this._emp_name = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
